name: Deploy Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Estos workflows se ejecutan en una VM, NO en el repositorio como tal.
      # Así que hay que descargar el código en la VM.
      - name: Get code on the server
        uses: actions/checkout@v4.2.2
      # Instalar Node js en la VM de ubuntu
      - name: Install NodeJS
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "latest"
        # Instalar dependencias
      - name: Install dependencies
        run:
          npm install
          # Ejecutar pruebas
      - name: Run tests
        run: npm test
  deploy:
    # needs indica que este workflow depende del anterior antes de comenzar a ejecutarse
    # Si es necesario, se pueden declarar como un array de dependencias
    # Ejemplo: needs: [test, build]
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Me traigo el codigo del repositorio
      - name: Get code on the server
        uses: actions/checkout@v4.2.2
      # Instalo NodeJS en la VM de ubuntu
      - name: Install NodeJS
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "latest"
      # Instalar dependencias del proyecto usando node
      - name: Install dependencies
        run: npm install
      # Compilar el proyecto
      - name: Build the project
        run: npm run build
      # Normalmente, ahora se sube a un host para servir el sitio web.
      # Pero en este caso, no se sube, solo se hace un echo..
      - name: Deploy
        run: echo "Deploying..."
